name: Test and Coverage

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        maven: ['3.8.5']
        java: ['21']
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Updated from v1 to v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}

      - name: Cache Maven dependencies
        uses: actions/cache@v3  # Updated to v3
        with:
          path: ~/.m2/repository
          key: maven-${{ runner.os }}-${{ matrix.java }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-${{ runner.os }}-${{ matrix.java }}-

      - name: Setup Maven
        uses: s4u/setup-maven-action@v1.18.0
        with:
          java-version: ${{ matrix.java }}
          maven-version: ${{ matrix.maven }}

      - name: Generate test coverage
        id: coverage
        run: |
          echo "compiling"
          mvn compile
          echo "testing"
          mvn test
          echo "jacoco reporting"
          mvn jacoco:report
          echo "extract coverage value"
          
          # Ensure the Jacoco report file exists before processing
          if [ -f target/site/jacoco/index.html ]; then
          display=$(grep -oP '(?<=<td>Total</td><td class="bar">).*?(?=%</td>)' target/site/jacoco/index.html | head -1)
          echo "display=$display%" >> $GITHUB_ENV    # with "%"
          coverage=${display}
          echo "coverage=$coverage" >> $GITHUB_ENV  # without "%"
          else
          echo "Jacoco report not found, setting coverage to 0"
          echo "display=0%" >> $GITHUB_ENV
          echo "coverage=0" >> $GITHUB_ENV
          fi

      - name: Extract branch name
        id: extract_branch
        run: echo "branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Checkout badges branch
        uses: actions/checkout@v3  # Updated from v1 to v3
        with:
          ref: badges
          path: badges

      - name: Create badges directory if necessary
        run: mkdir -p badges/${{ env.branch }}

      - name: Generate the badge SVG using Shields.io
        run: |
          COVERAGE=${{ env.coverage }}
          COLOR=$( 
            if [ "$COVERAGE" -gt 90 ]; then echo "green"; 
            elif [ "$COVERAGE" -gt 80 ]; then echo "yellowgreen"; 
            elif [ "$COVERAGE" -gt 70 ]; then echo "yellow"; 
            elif [ "$COVERAGE" -gt 60 ]; then echo "orange"; 
            else echo "red"; fi 
          )
          
          mkdir -p badges/${{ steps.extract_branch.outputs.branch }}
          curl -o badges/${{ steps.extract_branch.outputs.branch }}/badge.svg \
            "https://img.shields.io/badge/Test%20coverage-$COVERAGE%25-$COLOR.svg"


      - name: Commit & push badge
        run: |
          cd badges
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add "${{ env.branch }}/badge.svg"
          git commit -m "Add/Update badge" || echo "No changes to commit"

      - name: Push badge commit
        run: |
         cd badges
         git push origin badges

